### ISSUE TITLE
30 minutes limit on office online server documents

### ISSUE THREAD

**Issue by SteelPC** [roscomputing/richdocuments#125]
**Describe the bug**

If a document is left open or being modified for more than 30 minutes we get an error (file not found or accessible) and all modifications made after the 30 minutes mark are gone.

**To Reproduce**
1. Create a new document
2. Modify or leave it open for 30 minutes
3. Try to modify it after the 30 minutes mark

**Expected behavior**
Document should be editable after 30 minutes

**Client details:**
 - OS: Linux Mint 20, Windows 10
 - Browser Chrome
 - Version 90.0.4430.93
 - Device: desktop

## Server details

**Operating system**:

Nginx 1.19.6
10.5.9-MariaDB
PHP : 7.4.16
Nextcloud 20.0.9
Wopi app 3.5.6

**Comment by xklonx** [comment]
I will change the token life time to 10 hrs as recommended [here](https://wopi.readthedocs.io/projects/wopirest/en/latest/concepts.html#term-access-token-ttl). I will add a access_token_ttl
 passing so that the office can display an expiration warning.

**Comment by xklonx** [comment]
Try 3.5.7

**Comment by SteelPC** [comment]
So far so good. Edited a document for 2 hours no loss :)

**Comment by JustinWalravens** [comment]
If I understand correctly, it is necessary to modify the value of access_token. But what I don't understand is where in which file, config apache, Nextcloud

**Comment by xklonx** [comment]
You can change token lifetime in lib/Db/WopiMapper.php - TOKEN_LIFETIME_SECONDS

**Comment by JustinWalravens** [comment]
Thanks for the information.
But the Db folder does not exist on my system. (Debian)

**Comment by xklonx** [comment]
App files can be found in apps/wopi, so full path apps/wopi/lib/Db/WopiMapper.php

**Comment by JustinWalravens** [comment]
OK, I found.
Tank
