### ISSUE TITLE
File Conversion Fail

### ISSUE THREAD

**Issue by whisper1021** [roscomputing/richdocuments#2]
Hi,

I am using Nextcloud 18.0.1, WOPI App 3.4.10 and the latest version of Microsoft Office Online Server.

All operations are very good, but encountered a problem.

When I open a doc file, OOS Server will ask me to convert it, and an error message "file conversion fail" will pop up.

But the system actually copied a file called "New FIles.docx".

**Comment by xklonx** [comment]
Try 3.5.2 and let me know if you have any problems.

**Comment by xklonx** [comment]
I also made it to use the name of an existing file in 3.5.3
