### ISSUE TITLE
Nextcloud 22 compatibility

### ISSUE THREAD

**Issue by SteelPC** [roscomputing/richdocuments#236]
Do you have a time schedule for Nextcloud 22 compatibility ?

**Comment by xklonx** [comment]
I think next week

ср, 29 сент. 2021 г., 10:08 SteelPC ***@***.***>:

**Comment by Frenky007** [comment]
will be very appriciated. thx!

**Comment by xklonx** [comment]
Try 3.5.9

**Comment by SteelPC** [comment]
It's 3.5.10 apparently now :) It works with 21.0.4 and no more update notification error when looking at 22 update
