### ISSUE TITLE
Open files with local microsoft office

### ISSUE THREAD

**Issue by SteelPC** [roscomputing/richdocuments#294]
Is there anyway you could make a plugin to open and edit files from the nextcloud interface to the local microsoft office just like sharepoint does ? It would be a killer feature imo :)

**Comment by SteelPC** [comment]
I would actually be willing to pay for someone to code and maintain such plug-in. PM me if interested

**Comment by xklonx** [comment]
As far as i know desktop office apps doesnt support wopi, as said [here](https://stackoverflow.com/questions/37276654/edit-in-word-using-wopi-and-office-online-server) file opens trough webdav, so you can try to [install webdav plugin](https://docs.nextcloud.com/server/latest/user_manual/ru/files/access_webdav.html) in nextcloud, sync with any client and open file in destop app from filesystem.

**Comment by SteelPC** [comment]
Feature is available in NC 25
