### ISSUE TITLE
connection timed out

### ISSUE THREAD

**Issue by macleod5** [roscomputing/richdocuments#3]
Hello,

I'm using Nextcloud 18.0.1 with WOPI 3.5.4. But every time I try to open a document I get the following error: "The connection has timed out"

If i monitor the server's outgoing traffic I don't see any connection attempts towards the OOS.
But when I click on the Save button in the settings, I get the "Office Online server is reachable." message and I can also see the connection in iftop.
443 is open + I can access the https://server/hosting/discovery from the NC server

What could be the problem?

Thanks!

**Comment by xklonx** [comment]
Hi.
Where do you see this error?
Can you provide full error trace from log file?
Your browser must have access to https://server/hosting/discovery and urls in that discovery file.
Your oos server must have access to nextcloud at same address you access it.

**Comment by macleod5** [comment]
> Hi.
> Where do you see this error?
> Can you provide full error trace from log file?
> Your browser must have access to https://server/hosting/discovery and urls in that discovery file.
> Your oos server must have access to nextcloud at same address you access it.

Hi,
first of all sorry for my very late response. It was absolutely my fault. It was a problem with the firewall settings.
The app works perfectly.

Best regards and thanks for the reply,
Andrew
